# Generated by Django 6.0.5 on 2026-06-18 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do CLiente')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota de (1 a 5)')),
                ('comentario', models.TextField(max_length=500, verbose_name='Depoimento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
            ],
            options={
                'verbose_name': 'Avaliações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
