# Generated by Django 6.0.5 on 2026-06-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_rename_avaliacoes_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
