# Generated by Django 6.0.5 on 2026-06-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_avaliacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
